[build]
  publish = "dist"
  functions = "api/functions"
  command = "npm install && npm run build"

[build.environment]
  NPM_FLAGS = "--include=dev"
  NODE_ENV = "development"

[dev]
  command = "vite"
  targetPort = 5173
  publish = "dist"
  functions = "api/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
