[build]
  publish = "dist"
  functions = "api/functions"
  command = "npm run build"

[dev]
  command = "vite"
  targetPort = 5173
  publish = "dist"
  functions = "api/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
